[functions]
directory = "functions/"

[build]
command = """
mkdir functions &&
cargo zigbuild --release --target x86_64-unknown-linux-gnu.2.26 &&
cp target/x86_64-unknown-linux-gnu/release/fitness-tracking functions/
"""
